// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mail;

namespace mail.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260718224001_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mail.login_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IPV4")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("pc_user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("login_user");
                });

            modelBuilder.Entity("mail.mail_get_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alınan_mail_icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alınan_mail_konu")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("mail_alma_tarhi")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("yollayan_kisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.HasIndex("kisi_no");

                    b.ToTable("mail_get_user");
                });

            modelBuilder.Entity("mail.mail_get_user_bodyfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("alınan_mail_bodyfile")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("alınan_mail_no")
                        .HasColumnType("int");

                    b.Property<int>("height")
                        .HasColumnType("int");

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("alınan_mail_no");

                    b.ToTable("mail_get_user_bodyfile");
                });

            modelBuilder.Entity("mail.mail_get_user_dosyalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("alınan_mail_dosyalar")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("alınan_mail_no")
                        .HasColumnType("int");

                    b.Property<string>("attachment_name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("alınan_mail_no");

                    b.ToTable("mail_get_user_dosyalar");
                });

            modelBuilder.Entity("mail.mail_send_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("gonderilen_mail_icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gonderilen_mail_konu")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("mail_yollama_tarhi")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("kisi_no");

                    b.ToTable("mail_send_user");
                });

            modelBuilder.Entity("mail.mail_send_user_bodyfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("gonderilen_mail_bodyfile")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("gonderilen_mail_no")
                        .HasColumnType("int");

                    b.Property<int>("height")
                        .HasColumnType("int");

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("gonderilen_mail_no");

                    b.ToTable("mail_send_user_bodyfile");
                });

            modelBuilder.Entity("mail.mail_send_user_dosyalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attachment_name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<byte[]>("gonderilen_mail_dosyalar")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("gonderilen_mail_no")
                        .HasColumnType("int");

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("gonderilen_mail_no");

                    b.ToTable("mail_send_user_dosyalar");
                });

            modelBuilder.Entity("mail.trash_get_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alınan_mail_icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alınan_mail_konu")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("mail_alma_tarhi")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("yollayan_kisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.HasIndex("kisi_no");

                    b.ToTable("trash_get_user");
                });

            modelBuilder.Entity("mail.trash_get_user_bodyfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("alınan_mail_bodyfile")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("alınan_mail_no")
                        .HasColumnType("int");

                    b.Property<int>("height")
                        .HasColumnType("int");

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("alınan_mail_no");

                    b.ToTable("trash_get_user_bodyfile");
                });

            modelBuilder.Entity("mail.trash_get_user_dosyalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("alınan_mail_dosyalar")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("alınan_mail_no")
                        .HasColumnType("int");

                    b.Property<string>("attachment_name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("kisi_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("alınan_mail_no");

                    b.ToTable("trash_get_user_dosyalar");
                });

            modelBuilder.Entity("mail.mail_get_user", b =>
                {
                    b.HasOne("mail.login_user", "Kisi")
                        .WithMany("AlinanMailler")
                        .HasForeignKey("kisi_no")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.mail_get_user_bodyfile", b =>
                {
                    b.HasOne("mail.mail_get_user", "MailGetUser")
                        .WithMany("Bodyfiles")
                        .HasForeignKey("alınan_mail_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.mail_get_user_dosyalar", b =>
                {
                    b.HasOne("mail.mail_get_user", "MailGetUser")
                        .WithMany("Dosyalar")
                        .HasForeignKey("alınan_mail_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.mail_send_user", b =>
                {
                    b.HasOne("mail.login_user", "Kisi")
                        .WithMany("GonderilenMailler")
                        .HasForeignKey("kisi_no")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.mail_send_user_bodyfile", b =>
                {
                    b.HasOne("mail.mail_send_user", "MailSendUser")
                        .WithMany("Bodyfiles")
                        .HasForeignKey("gonderilen_mail_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.mail_send_user_dosyalar", b =>
                {
                    b.HasOne("mail.mail_send_user", "MailSendUser")
                        .WithMany("Dosyalar")
                        .HasForeignKey("gonderilen_mail_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.trash_get_user", b =>
                {
                    b.HasOne("mail.login_user", "Kisi")
                        .WithMany("SilinenMailler")
                        .HasForeignKey("kisi_no")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.trash_get_user_bodyfile", b =>
                {
                    b.HasOne("mail.trash_get_user", "TrashGetUser")
                        .WithMany("Bodyfiles")
                        .HasForeignKey("alınan_mail_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mail.trash_get_user_dosyalar", b =>
                {
                    b.HasOne("mail.trash_get_user", "TrashGetUser")
                        .WithMany("Dosyalar")
                        .HasForeignKey("alınan_mail_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
